### ISSUE TITLE
点击动漫播放的时候出现Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by SingerDracula** [antigenMHC/ErCiYuan#1]
点击
![image](https://user-images.githubusercontent.com/29811296/141614560-a16efda0-3b3f-4d60-ba36-fd9b4365d236.png)
这个地方的时候出现了
![image](https://user-images.githubusercontent.com/29811296/141614573-85289714-1d24-4060-a4c6-fe79996c126a.png)

**Comment by antigenMHC** [comment]
需要和阿里云的 vod 配合使用，将 videoId 传入后端的 videoApi 来获取视频信息，可以查看后端日志。建议清空数据后重新录入再次尝试

**Comment by iwakura-lain** [comment]
> 点击 ![image](https://user-images.githubusercontent.com/29811296/141614560-a16efda0-3b3f-4d60-ba36-fd9b4365d236.png) 这个地方的时候出现了 ![image](https://user-images.githubusercontent.com/29811296/141614573-85289714-1d24-4060-a4c6-fe79996c126a.png)

需要和阿里云的 vod 配合使用，将 videoId 传入后端的 videoApi 来获取视频信息，可以查看后端日志。建议清空数据后重新录入再次尝试

**Comment by SingerDracula** [comment]
> > 点击 ![image](https://user-images.githubusercontent.com/29811296/141614560-a16efda0-3b3f-4d60-ba36-fd9b4365d236.png) 这个地方的时候出现了 ![image](https://user-images.githubusercontent.com/29811296/141614573-85289714-1d24-4060-a4c6-fe79996c126a.png)
> 
> 需要和阿里云的 vod 配合使用，将 videoId 传入后端的 videoApi 来获取视频信息，可以查看后端日志。建议清空数据后重新录入再次尝试

在后端debug了一下，确定是可以拿到视频的url的，并且把url直接复制到浏览器是可以看的。还是发现这个问题。
![image](https://user-images.githubusercontent.com/29811296/141645366-98d72ad8-657e-4ab1-b099-c3a3c747b5f8.png)

**Comment by SingerDracula** [comment]
弄好了，是数据库有重复的数据导致的。感谢作者的帮助
